# Generated by Django 3.1.1 on 2022-08-04 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cheeses', '0002_remove_cheese_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheese',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='Name of Cheese'),
            preserve_default=False,
        ),
    ]
